// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-canXjBRg96_6zWTeVypQF9EPeW99ncU',
    appId: '1:819413446346:web:6cefaaaf1bb69243624e33',
    messagingSenderId: '819413446346',
    projectId: 'qw1fc4r89dqnxus9zuyejk7u8wiozy',
    authDomain: 'qw1fc4r89dqnxus9zuyejk7u8wiozy.firebaseapp.com',
    storageBucket: 'qw1fc4r89dqnxus9zuyejk7u8wiozy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNCLfeNCE1jyHpQxxj3feQWKA8y40Zfg',
    appId: '1:819413446346:android:b5f081fc985e9138624e33',
    messagingSenderId: '819413446346',
    projectId: 'qw1fc4r89dqnxus9zuyejk7u8wiozy',
    storageBucket: 'qw1fc4r89dqnxus9zuyejk7u8wiozy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbzdwUPa2f7FRn8tdTGRKDHOsqneUspNs',
    appId: '1:819413446346:ios:4396b9159b2fcd0d624e33',
    messagingSenderId: '819413446346',
    projectId: 'qw1fc4r89dqnxus9zuyejk7u8wiozy',
    storageBucket: 'qw1fc4r89dqnxus9zuyejk7u8wiozy.firebasestorage.app',
    iosBundleId: 'com.nomiapps.artty',
  );
}
